workflows:
  ios-workflow:
    name: iOS SwiftPM Workflow
    environment:
      vars:
        APPLE_ID: "kiryushinrus@gmail.com"  # Ваш Apple ID
        APPLE_PASSWORD: "tids-oakg-oryo-vkmt"  # App-specific password, который вы создали
      xcode: latest
    scripts:
      - name: Resolve dependencies
        script: swift package resolve
      - name: Build the app
        script: xcodebuild -scheme "My App" -sdk iphoneos -configuration Release
    artifacts:
      - build/ios/ipa/*.ipa
